const S=require('../schedule-data.js'),T=require('./transfers.cjs');
const schema=`CREATE TABLE IF NOT EXISTS trip_timetables(route_id INTEGER NOT NULL,trip_id TEXT NOT NULL,service_date TEXT NOT NULL,stops_json TEXT NOT NULL,metadata_json TEXT NOT NULL,captured_at REAL NOT NULL,PRIMARY KEY(route_id,service_date,trip_id));`;
const archiveSql=`INSERT INTO trip_timetables SELECT json_extract(value,'$.route_id'),json_extract(value,'$.trip_id'),json_extract(value,'$.service_date'),json_extract(value,'$.stops_json'),json_extract(value,'$.metadata_json'),json_extract(value,'$.captured_at') FROM json_each(?) WHERE 1 ON CONFLICT DO NOTHING`;
function options(url){const routeId=Number(url.searchParams.get('route')),date=url.searchParams.get('date'),tripId=url.searchParams.get('trip')||'',startTime=url.searchParams.get('start')??'';if(!Number.isInteger(routeId)||routeId<1||!S.validDate(date)||tripId.length>160||!/^(?:\d{1,2}:[0-5]\d:[0-5]\d)?$/.test(startTime))throw Error('Choose a tracked route, valid service date and trip');return {routeId,date,tripId,startTime};}
const asset=route=>`${route.mode==='bus'?3:2}-${route.code}.json`;
function active(data,service,date){const day=date.replaceAll('-',''),exception=data.exceptions.find(r=>r.service_id===service&&r.date===day);if(exception)return exception.exception_type==='1';const c=data.calendar.find(r=>r.service_id===service);return !!c&&day>=c.start_date&&day<=c.end_date&&c[['sunday','monday','tuesday','wednesday','thursday','friday','saturday'][new Date(date+'T12:00:00Z').getUTCDay()]]==='1';}
function timetable(data,tripId,date,routeId){const trip=data?.trips.find(t=>t.id===tripId&&active(data,t.service,date));if(!trip)return null;const base=S.serviceBase(date);return {route_id:routeId,trip_id:tripId,service_date:date,stops_json:JSON.stringify(trip.stops.map(s=>({sequence:s[0],stopId:s[1],name:data.stops[s[1]],scheduledArrival:s[2]==null?null:base+s[2],scheduledDeparture:s[3]==null?null:base+s[3],pickup:s[4],dropoff:s[5]}))),metadata_json:JSON.stringify({destination:trip.destination,direction:trip.direction,source:data.source,feedVersion:data.feed.feed_version,validUntil:data.feed.feed_end_date,generatedAt:data.generatedAt}),captured_at:Date.now()/1000};}
async function sync(store,routes,batch,loader){const unique=new Map();for(const e of [...batch.events,...(batch.adherence||[]),...(batch.cancellations||[])])unique.set(JSON.stringify([e.routeId,e.tripId,e.serviceDate]),{route_id:e.routeId,trip_id:e.tripId,service_date:e.serviceDate});const missing=await store.missingTimetables([...unique.values()]);const cache=new Map(),rows=[];for(const e of missing){const route=routes.find(r=>r.id===e.route_id);if(!route)continue;const name=asset(route);if(!cache.has(name))cache.set(name,await loader(name));const row=timetable(cache.get(name),e.trip_id,e.service_date,e.route_id);if(row)rows.push(row);}await store.archiveTimetables(rows);return rows.length;}
function list(data,archives,events,cancellations,{routeId,date},now=Date.now()/1000){const trips=new Map(),base=S.serviceBase(date);for(const t of data?.trips||[]){if(!active(data,t.service,date))continue;const first=t.stops[0],seconds=first?.[3]??first?.[2];trips.set(t.id,{tripId:t.id,startTime:'',scheduledStart:seconds==null?null:base+seconds,destination:t.destination,stopCount:t.stops.length});}for(const a of archives){const stops=JSON.parse(a.stops_json),meta=JSON.parse(a.metadata_json);trips.set(a.trip_id,{tripId:a.trip_id,startTime:'',scheduledStart:stops[0]?.scheduledDeparture??stops[0]?.scheduledArrival,destination:meta.destination,stopCount:stops.length});}
 const instances=new Map();for(const e of events){const k=JSON.stringify([e.trip_id,e.start_time]);if(!instances.has(k))instances.set(k,{...(trips.get(e.trip_id)||{tripId:e.trip_id,destination:'Timetable unavailable'}),startTime:e.start_time,observations:0});instances.get(k).observations++;}for(const c of cancellations){const k=JSON.stringify([c.trip_id,c.start_time]);if(!instances.has(k))instances.set(k,{...(trips.get(c.trip_id)||{tripId:c.trip_id}),startTime:c.start_time,observations:0});instances.get(k).cancelled=true;}
 const observedIds=new Set([...instances.values()].map(t=>t.tripId));return [...instances.values(),...[...trips.values()].filter(t=>!observedIds.has(t.tripId)).map(t=>({...t,observations:0}))].map(t=>({...t,status:t.cancelled?'Cancelled':t.observations?'Reports captured':t.scheduledStart>now?'Scheduled':'No reports captured'})).sort((a,b)=>(a.scheduledStart??Infinity)-(b.scheduledStart??Infinity)||a.tripId.localeCompare(b.tripId));}
function endpoints(stops,rows,cancelled){
 const planned=[...stops].sort((a,b)=>a.sequence-b.sequence);
 const point=(stop,kind)=>{
  if(!stop)return {kind,status:cancelled?'Cancelled':'Timetable unavailable',delay:null,time:null,scheduled:null};
  const row=rows.find(s=>s.sequence===stop.sequence&&s.stopId.replace(/-[a-f\d]{6,}$/i,'')===stop.stopId.replace(/-[a-f\d]{6,}$/i,''));
  return {stopId:stop.stopId,name:stop.name,sequence:stop.sequence,kind,...row[kind]};
 };
 // Endpoints require the full timetable; the first/last captured report may be
 // an intermediate stop. Loops are distinguished by sequence, not stop ID.
 return {start:point(planned[0],'departure'),end:point(planned.at(-1),'arrival')};
}
function detail(archive,events,cancelled,selection,now=Date.now()/1000){const stops=archive?JSON.parse(archive.stops_json):[],metadata=archive?JSON.parse(archive.metadata_json):null,byStop=new Map(stops.map(s=>[JSON.stringify([s.sequence,s.stopId.replace(/-[a-f\d]{6,}$/i,'')]),{...s}]));
 for(const e of events.filter(e=>e.start_time===selection.startTime)){const k=JSON.stringify([e.sequence,e.stop_id.replace(/-[a-f\d]{6,}$/i,'')]);if(!byStop.has(k))byStop.set(k,{sequence:e.sequence,stopId:e.stop_id,name:T.stopName(e.stop_id),scheduledArrival:null,scheduledDeparture:null});const stop=byStop.get(k),old=stop[e.kind];if(!old||e.reported_at>old.reportedAt)stop[e.kind]={time:e.event_time,delay:e.delay_sec,reportedAt:e.reported_at,derivedSchedule:e.scheduled_time};}
 const rows=[...byStop.values()].sort((a,b)=>a.sequence-b.sequence);for(const s of rows){for(const kind of ['arrival','departure']){const key=kind==='arrival'?'scheduledArrival':'scheduledDeparture',event=s[kind],scheduled=s[key];s[kind]={...event,time:event?.time??null,delay:event?.delay??(event&&scheduled!=null?event.time-scheduled:null),scheduled:scheduled??event?.derivedSchedule??null,scheduleSource:scheduled!=null?'GTFS':event?.derivedSchedule!=null?'Derived from reported delay':null,status:cancelled?'Cancelled':event?'Reported':scheduled!=null&&scheduled>now?'Pending':'Not captured'};}s.dwellSeconds=s.arrival.time!=null&&s.departure.time!=null&&s.departure.time>=s.arrival.time?s.departure.time-s.arrival.time:null;}
 return {...selection,metadata,completeStopList:!!archive,cancelled,stops:rows,endpoints:endpoints(stops,rows,cancelled),summary:{stops:rows.length,arrivals:rows.filter(s=>s.arrival.time!=null).length,departures:rows.filter(s=>s.departure.time!=null).length}};}
async function view(store,selection,loader){
 if(selection.date<require('./retention.cjs').policy().cutoff)throw Error('Trip history is retained for three calendar months');
 const route=(await store.routes()).find(r=>r.id===selection.routeId);if(!route)throw Error('Tracked route not found');
 const saved=await store.tripData(selection);let data=null;
 // An archived trip remains usable even when the current timetable is unavailable.
 if(!selection.tripId||!saved.archives.length){try{data=await loader(asset(route));}catch{data=null;}}
 if(!selection.tripId)return {route,date:selection.date,trips:list(data,saved.archives,saved.events,saved.cancellations,selection),timetable:data?{source:data.source,validUntil:data.feed.feed_end_date,generatedAt:data.generatedAt}:null};
 let archive=saved.archives[0];if(!archive&&data){archive=timetable(data,selection.tripId,selection.date,selection.routeId);if(archive)await store.archiveTimetables([archive]);}
 if(!archive&&!saved.events.length&&!saved.cancellations.length)throw Error('Trip not found for this route and service date');
 const cancelled=saved.cancellations.some(c=>c.start_time===selection.startTime);
 return {route,...detail(archive,saved.events,cancelled,selection)};
}
module.exports={schema,archiveSql,options,asset,active,timetable,sync,list,detail,view};
